### PR TITLE
Drop support php lower 7.3

### PR DESCRIPTION
**Pull request by Yozhef**

### CODE REVIEW

**Comment by Yozhef** [comment]
https://github.com/Yozhef/oauth2-facebook/pull/1 - all check is green

**Review by shadowhand — APPROVED** [review]

**Comment by shadowhand** [comment]
@Yozhef 👍 good stuff, thanks!

**Comment by shadowhand** [comment]
@Yozhef is there anything else that needs to be done before a release?

**Comment by Yozhef** [comment]
@shadowhand if you have a rule add this service to https://codecov.io/ maybe adding integrations?

**Comment by shadowhand** [comment]
@Yozhef codecov is enabled.

**Pull request merged**
