### PR TITLE
getAvatar should be getImageurl to match the othe providers

### PR DESCRIPTION
**Pull request by vipconsult**

### CODE REVIEW

**Comment by ramsey** [comment]
Since properties of the resource owner ("user") aren't defined by OAuth 2.0, I think it's acceptable for each provider to have different methods and names for these properties, according to what the service (in this case, Facebook) calls them.

**Comment by vipconsult** [comment]
so then in the app logic I should have if else blocks to get the properties for each provider ?

**Comment by ramsey** [comment]
Could you explain your use-case in greater detail? I want to understand what it is you're trying to accomplish.

As I said, the properties of each resource owner are not defined by the OAuth 2.0 specification. In earlier versions of the oauth2-client library, there were too many properties being added to the "User" that were only needed by one or two of the providers, so things were getting out of hand, and it was impossible to cover all needs. In your particular case, not all providers need to implement a `getImageUrl()` method, so it doesn't make sense to force them to provide it. As a result, we made the decision not to force each individual provider to adhere to a strict interface for the resource owner.

The only thing we ask is that "users" (or resource owners) implement the `ResourceOwnerInterface` and they provide a `getId()` method. An ID is the only thing we can more-or-less safely assume will be available in most providers.

**Comment by vipconsult** [comment]
here is the generic code which i had with the previous versions of oauth so need to refaktor it to handle the properties for each porivider.

i am using , google , fb , linkedin, mikrosoft

function authenticate($provider_name){
        try {
            require_once('application/libraries/OAuth2League/vendor/autoload.php');

            $ci->config->load('oauth');

            $class_namespace="\League\OAuth2\Client\Provider\\".$provider_name;

            $params=$ci->config->item($provider_name);

            if(empty($params)){
                throw new Exception('Invalid Authentication Provider:'.$provider_name);
                session_message("Invalid Authentication Provider!",'error');
                return FALSE;
                
            }

            $provider =new $class_namespace($params);

            if (!isset($_GET['code'])) {
                // If we don't have an authorization code then get one
                $authUrl = $provider->getAuthorizationUrl();
                $_SESSION['oauth2state'] = $provider->getState();
                header('Location: '.$authUrl);
                exit;
            // Check given state against previously stored one to mitigate CSRF attack
            } 
            elseif (empty($_GET['state']) || ($_GET['state'] !== $_SESSION['oauth2state'])) {

                unset($_SESSION['oauth2state']);
                throw new Exception('Invalid state:'.print_r($_SESSION,1));

            }
            else {
                // Try to get an access token (using the authorization code grant)
                $token = $provider->getAccessToken('authorization_code', [
                    'code' => $_GET['code']
                ]);

                // Optional: Now you have a token you can look up a users profile data

                // We got an access token, let's now get the user's details
                $userDetails = $provider->getResourceOwner($token);

                $result_array=array(
                  'password'=>$userDetails->getId(),
                  'email'=>$userDetails->getEmail(),
                  'first_name'=>$userDetails->getFirstName(),
                  'last_name'=>$userDetails->getLastName(),
                  'avatar'=>$userDetails->getImageurl(),
                  'provider'=>$provider_name
                );
                
                //this is needed so that we use the built in validation rules
                $_POST['password']=$result_array['password'];
                $_POST['email']=$result_array['email'];

                $ci->session->set_userdata('oauth',$result_array);
                return TRUE;
                

                // Use this to interact with an API on the users behalf
                //echo $token->getToken();

                // Use this to get a new access token if the old one expires
                //echo $token->getRefreshToken();

                // Unix timestamp of when the token will expire, and need refreshing
                //echo $token->getExpires();
            }
        }
        catch (Exception $e) {
            send_email_shot(print_r("Login Failed:".$e,TRUE));
            return FALSE;
        }
}

**Comment by ramsey** [comment]
I'll leave the decision up to @SammyK. Please fix the tests in your PR, though. Changing the method name has caused the tests to fail. :-)

Since not all providers will have need for the `getEmail()`, `getFirstName()`, `getLastName()`, or `getImageurl()` methods, when you add a new provider that doesn't support one of these methods, this code will break. Not all providers need these methods, so I don't think it's acceptable to force them to implement them.

**Comment by vipconsult** [comment]
i completely agree but but how would i make my code generic again ? any suggestions ?

and getId is enforced so maybe adding email and picture url is not a big deal since all provider will support this anyway and it is included in the default scopes.

**Comment by ramsey** [comment]
There are providers who don't support email or picture.

I'll try to give some thought on how you can make your code more generic. Perhaps a few others can chime in, too.

**Comment by SammyK** [comment]
Hey @vipconsult! Thanks for the feedback. I'm with @ramsey on this one. The user entity is provider-specific and should follow the domain-specific naming conventions of the provider. In this case Facebook calls the user profile image a "picture" so it makes sense to keep the method `getPictureUrl()`.

The key is to make sure you're writing your code in a generic way that you can extend from and customize for each provider. It might help to have another coder to look over your code to brainstorm a way to make it more flexible.

Good luck with your project! :)

**Comment by vipconsult** [comment]
ok.

i am on mu own on this one so if you give me some small pointers it would be of great help.

**Pull request closed without merging**
