### PR TITLE
Upgrading the Provider for compatibility with alpha1

### PR DESCRIPTION
**Pull request by weaverryan**
Hiya Sammy!

I don't know how much more will change before a stable release of the OAuth2 client (and so I don't know if you're trying to follow it closely or basically wait until the dust has settled), but here are some changes that seem to make everything happy with alpha1 :). I'm making tutorial for something, and I'm *hoping* to use the OAuth2 client to make my (and everyone's) life easier - even if it's alpha. I really like the idea.

Thanks!

### CODE REVIEW

**Comment by ramsey** [comment]
At this point, the API for oauth2-client shouldn't change. It's in alpha to give providers a chance to review and upgrade, as well as find issues that need to be resolved before a final 1.0.0 release.

**Comment by weaverryan** [comment]
Thanks Ben - really happy to hear that!

**Comment by ramsey** [comment]
Actually, I'll revise what I said about the API not changing…

Take a look at https://github.com/thephpleague/oauth2-client/issues/362. I'll be doing a 1.0.0-alpha2 release this Saturday. Following that will be a beta1 release (probably after another week). As of the beta1 release, I am putting a freeze on the API.

**Comment by weaverryan** [comment]
@ramsey good plan - really happy to see that things are moving more than anything else - when releases get neglected and stall, that's very difficult (this is clearly not that situation). Thanks!

**Comment by SammyK** [comment]
Thank you sir! :)

**Comment by weaverryan** [comment]
Yes! :fireworks:

**Pull request merged**
