### PR TITLE
Fix #27 Remove bio field for graphApiVersion greater than 2.8 at reso…

### LINKED ISSUE #27: Deprecated  field for versions v2.8
Hi
There is an error.

image

### PR DESCRIPTION
**Pull request by jerowork**
…urceOwnerDetails

### CODE REVIEW

**Comment by Chrico** [comment]
I guess the provider also needs an update, since the `bio` field is now moved into `about` ? (see changelog posted in #27 ).

**Comment by jerowork** [comment]
I thought so too at first, but when you look at the documentation of the User object (https://developers.facebook.com/docs/graph-api/reference/user/) many other fields existing in that object are not by default accessible by a method in FacebookUser(). 

Since 'about' is not a default field returned by the api (but only with an extended user permissions set) I did not add 'about' instead of 'bio' but just removed 'bio'. 

I could be wrong ofcourse, hoped that for example Sammy would know more about the restrictions of the basic set in FacebookUser().

**Comment by Chrico** [comment]
Sounds good to me.  Will add some more questions about this into #27

**Comment by SammyK** [comment]
Thanks so much for this! :)

**Pull request merged**
